### ISSUE TITLE
[경기도] 녹전연 개선 내용 반영

### ISSUE THREAD

**Issue by anne-parti** [parti-coop/parti-mx-spa#129]
새로 만드는 도미니 프로젝트에 녹전연 작업하면서 개선된 내용이 반영되는지 잘 몰라서 올리는 이슈입니다.
아래 개선 사항들이 혹시 반영되어 있지 않다면 도미니에도 반영해주세요.
(2, 3, 4, 5는 믹스 1.0에도 반영되면 좋겠네요)

1. 메인 지도 핀 게시판별 구별(색깔, 클릭 시 게시판 이름 노출). https://github.com/parti-coop/parti-mx-spa/issues/87
2. 제안, 투표, 모임기간 종료 후 관리자가 수정 가능하도록 변경. https://github.com/parti-coop/parti-mx-spa/issues/94
3. 검색 결과 페이지 개선. https://github.com/parti-coop/parti-mx-spa/issues/95
4. 소식 게시판 타입 목록 뷰 선택 옵션. https://github.com/parti-coop/parti-mx-spa/issues/96
5. 조회수 표시. https://github.com/parti-coop/parti-mx-spa/issues/97

**Comment by jenna1k** [comment]
- [ ]  메인 지도 핀 게시판별 구별(색깔, 클릭 시 게시판 이름 노출). #87
- [ ] 제안, 투표, 모임기간 종료 후 관리자가 수정 가능하도록 변경. #94
- [x] 검색 결과 페이지 개선. #95
- [x] 소식 게시판 타입 목록 뷰 선택 옵션. #96 - [소식게시판 보기 타입 선택 옵션없이 모두 미리보기 타입으로 바꾸고 후기게시판만 기존 형식](https://github.com/parti-coop/parti-mx-spa/issues/117#issuecomment-785724232)
- [x] 조회수 표시. #97
